get:
  tags:
    - ValidatorRequiredApi
    - Validator
  operationId: "proposerConfig"
  summary: "Produce a proposer config"
  description: |
    Requests the beacon node or DV middleware to produce the proposer config. The proposer_config enables validator registrations
    for distributed validator (DV) middleware clients.
  responses:
    "200":
      description: Success response
      content:
        application/json:
          schema:
            title: ProposerConfigResponse
            type: object
            properties:
              data:
                $ref: '../../beacon-node-oapi.yaml#/components/schemas/ProposerConfig'
    "400":
      $ref: '../../beacon-node-oapi.yaml#/components/responses/InvalidRequest'
    "500":
      $ref: '../../beacon-node-oapi.yaml#/components/responses/InternalError'
